In [1]:
import numpy as np

A=np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal =A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [7]:
percentage=100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [5]:
A.T

array([[ 56. ,   1.2,   1.8],
       [  0. , 104. , 135. ],
       [  4.4,  52. ,  99. ],
       [ 68. ,   8. ,   0.9]])

In [10]:
A=np.random.randn(32,32,3)

In [13]:
A=A.reshape((32*32*3,1))

In [14]:
A=np.random.randn(3,3)
B=np.random.randn(3,1)
A*B


array([[-0.29964   , -0.19617557, -0.05464039],
       [ 0.01168788,  0.04261171,  0.02559933],
       [-0.10262327, -0.07639115, -0.02043205]])